FROM python:3.7

ENV PYTHONUNBUFFERED 1

WORKDIR /app
COPY ./app/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./app .
COPY ./app/gunicorn.py /etc/gunicorn/gunicorn.py
RUN mkdir /tmp_gunicorn

CMD bash -c "python /app/manage.py migrate && gunicorn -c /etc/gunicorn/gunicorn.py app.wsgi"