version: '3.4'

services:

  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "8000:8000"

  redis:
    ports:
      - "6379:6379"


  postgres:
    image: 'postgres:10-alpine'
    ports:
      - '5432:5432'

