version: '3.4'

services:

  front_app:
    build:
      context: '.'
      dockerfile: ./app.Dockerfile

    command: bash -c "FLASK_ENV=development FLASK_APP=front_app flask run --host=0.0.0.0 --port 8000"

    ports:
      - "8000:8000"

    volumes:
      - ./front_app.py:/app/front_app.py

    networks:
      - api_network

networks:
  api_network:
    external:
      # compose creates network <dir>_default if not specified otherwise
      name: api_default
