version: '3.4'

services:

  nginx:

    build:
      context: '.'
      dockerfile: ./nginx.Dockerfile

    ports:
      - "8888:8888"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app

  app:
    build:
      context: '.'
      dockerfile: ./app.Dockerfile
    volumes:
      - ./main.py:/app/main.py

    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"


  postgres:
    image: 'postgres:10-alpine'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
