version: '3.4'

services:

  api:

    build:
      context: '.'
      dockerfile: ./app.Dockerfile

    command: bash -c "FLASK_ENV=development FLASK_APP=api flask run --host=0.0.0.0 --port 8888"

    ports:
      - "8888:8888"

    volumes:
      - ./api.py:/app/api.py
